### ISSUE TITLE
avrdude: invalid option -s

### ISSUE THREAD

**Issue by kr15uk** [vonnieda/AVRFuses#14] opened 2022-08-21 08:25 UTC
Not sure which is the problem AVRDUDE, AVRFuses or me being on macOS Ventura Public Beta (very likely)

I have latest AVRFuses 1.5.2 and AVRDUDE 7.0 from brew and USBasp as hardware

When I do AutoDetect or anything tbh I get this output:

```
Loading avrdude config...
SUCCESS
Reading signature...
avrdude: invalid option -s

Usage: avrdude [options]
Options:
  -p <partno>                Required. Specify AVR device.
  -b <baudrate>              Override RS-232 baud rate.
  -B <bitclock>              Specify JTAG/STK500v2 bit clock period (us).
  -C <config-file>           Specify location of configuration file.
  -c <programmer>            Specify programmer type.
  -D                         Disable auto erase for flash memory
  -i <delay>                 ISP Clock Delay [in microseconds]
  -P <port>                  Specify connection port.
  -F                         Override invalid signature check.
  -e                         Perform a chip erase.
  -O                         Perform RC oscillator calibration (see AVR053). 
  -U <memtype>:r|w|v:<filename>[:format]
                             Memory operation specification.
                             Multiple -U options are allowed, each request
                             is performed in the order specified.
  -n                         Do not write anything to the device.
  -V                         Do not verify.
  -t                         Enter terminal mode.
  -E <exitspec>[,<exitspec>] List programmer exit specifications.
  -x <extended_param>        Pass <extended_param> to programmer.
  -v                         Verbose output. -v -v for more.
  -q                         Quell progress output. -q -q for less.
  -l logfile                 Use logfile rather than stderr for diagnostics.
  -?                         Display this usage.

avrdude version 7.0, URL: <https://github.com/avrdudes/avrdude>
FAILURE
```

What is -s, did AVRDUDE just dropped it or my OS os making AVRFuses to do something funny here?!

Thanks

**Comment by vonnieda** [comment] 2022-08-21 19:51
Duplicate of #13. Working on that now.

**Closed as completed by vonnieda** 2022-08-21 19:51 UTC
